# Overrides base docker-compose.yml file
# to add stateful backing services (e.g. databases)

services:
  # PostgreSQL database
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-q"]
      start_period: 10s

  ## Neo4j graph database
  neo4j:
    image: neo4j:4.4-community
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - neo4j:/var/lib/neo4j/data
    healthcheck:
      test: ["CMD", "wget", "localhost:7474", "-O", "-"]
      start_period: 1m

  ## Apache Solr search engine
  solr:
    image: solr:9
    restart: unless-stopped
    command:
      - solr-precreate
      - file
    ports:
      - 8983
    volumes:
      - solr:/var/solr
    healthcheck:
      test:
        ["CMD", "curl", "-f", "localhost:8983/solr/admin/cores?action=STATUS"]
      start_period: 1m

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  ## Elasticsearch search engine
  elasticsearch:
    build:
      context: ..
      dockerfile: docker/elasticsearch.Dockerfile
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health"]
      start_period: 30s

  appserver:
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - NEO4J_HOST=neo4j
      - NEO4J_AUTH=neo4j/password
      - SOLR_URL=http://solr:8983/solr
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - neo4j
      - solr

  statistical-enrichment:
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_AUTH=neo4j/password
      - REDIS_HOST=redis
    depends_on:
      - neo4j
      - redis

  cache-invalidator:
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_AUTH=neo4j/password
      - REDIS_HOST=redis
    depends_on:
      - neo4j
      - redis

volumes:
  postgres:
  neo4j:
  solr:
