# Overrides base docker-compose.yml file for running in development mode.
version: "3.8"

services:
  frontend:
    build:
      context: ../client
      target: angular-build
      args:
        - ANGULAR_CONFIG=dev
    ports:
      - 4200:4200
    environment:
      APPSERVER_URL: http://appserver:5000

  appserver:
    build:
      context: ../appserver
      args:
        DEV: 1
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FRONTEND_URL=http://localhost:4200
      # Unset to use the default LMDB data directory
      - LMDB_DATA_DIR=
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE_PATH:-..}/appserver
        target: /app
    user: root

  statistical-enrichment:
    build:
      context: ../statistical-enrichment
      args:
        DEV: 1
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE_PATH:-..}/statistical-enrichment
        target: /app
    user: root

  cache-invalidator:
    build:
      context: ../cache-invalidator
      args:
        DEV: 1
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE_PATH:-..}/cache-invalidator
        target: /app
    user: root

  solr:
    image: solr:9
    command:
      - solr-precreate
      - file
    healthcheck:
      start_period: 45s
