# Overrides base docker-compose.yml file for running in development mode.
version: "3.8"

services:
  frontend:
    build:
      context: ../client
      args:
        - ANGULAR_CONFIG=dev
    environment:
      APPSERVER_URL: http://appserver:5000

  appserver:
    build:
      context: ../appserver
      args:
        DEV: 1
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FRONTEND_URL=http://localhost:8080
      # Unset to use the default LMDB data directory
      - LMDB_DATA_DIR=
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE_PATH:-..}/appserver
        target: /app
    user: root

  statistical-enrichment:
    build:
      context: ../statistical-enrichment
      args:
        DEV: 1
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE_PATH:-..}/statistical-enrichment
        target: /app
    user: root

  cache-invalidator:
    build:
      context: ../cache-invalidator
      args:
        DEV: 1
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE_PATH:-..}/cache-invalidator
        target: /app
    user: root

  mozg:
    build:
      context: ../mozg
    environment:
      - NODE_ENV=development

  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.store.allow_mmap=false
      - xpack.ml.enabled=false
    healthcheck:
      start_period: 90s
